name: DEPLOY REALMS

on:
  workflow_dispatch:
    inputs:
        realm_name:
            description: 'Name of realm'
            required: true

jobs:
    apply:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: setup OpenTofu
              uses: opentofu/setup-opentofu@v1

            - name: Init
              run: tofu init
              working-directory: realms/

            - name: Apply
              env: 
                TF_VAR_realm_name: ${{ github.event.inputs.realm_name }}
              run: tofu apply -auto-approve
              working-directory: realms/

             